
export const KALP_HYBRID_COLUMN_CONFIG = [
  { name: 'Device No', prop: 'Device No' },
  { name: 'Dongle No', prop: 'Dongle No' },
  { name: 'Date', prop: 'Date' },
  { name: 'Time', prop: 'Time' },
  { name: 'Customer Name', prop: 'Customer Name' },
  { name: 'Software Version', prop: 'Software Version' },
  { name: 'M66 Version', prop: 'M66 Version' },
  { name: 'Device Status', prop: 'Device Status' },
  { name: 'Signal strength', prop: 'Signal strength' },
  { name: 'Fault bit 1', prop: 'Fault bit 1' },
  { name: 'Fault bit 2', prop: 'Fault bit 2' },
  { name: 'Temperature(<sup>o</sup>C)', prop: 'Temperature(<sup>o</sup>C)' },
  { name: 'Motor Volt(V)', prop: 'Motor Volt(V)' },
  { name: 'Motor Amp(A)', prop: 'Motor Amp(A)' },
  { name: 'Motor Freq(Hz)', prop: 'Motor Freq(Hz)' },
  { name: 'Motor Power(kW)', prop: 'Motor Power(kW)' },
  { name: 'Flow(LPM)', prop: 'Flow(LPM)' },
  { name: 'Speed(RPM)', prop: 'Speed(RPM)' },
  { name: 'Today Energy VFD(kWh)', prop: 'Today Energy VFD(kWh)' },
  { name: 'Today Time VFD(Hr)', prop: 'Today Time VFD(Hr)' },
  { name: 'Total Energy VFD(kWh)', prop: 'Total Energy VFD(kWh)' },
  { name: 'Total Time VFD(Hr)', prop: 'Total Time VFD(Hr)' },
  { name: 'Total Flow(ML)', prop: 'Total Flow(ML)' },
  { name: 'PV1 Volt(V)', prop: 'PV1 Volt(V)' },
  { name: 'PV1 Amp(A)', prop: 'PV1 Amp(A)' },
  { name: 'PV2 Volt(V)', prop: 'PV2 Volt(V)' },
  { name: 'PV2 Amp(A)', prop: 'PV2 Amp(A)' },
  { name: 'R-Phase Volt(V)', prop: 'R-Phase Volt(V)' },
  { name: 'Y-Phase Volt(V)', prop: 'Y-Phase Volt(V)' },
  { name: 'B-Phase Volt(V)', prop: 'B-Phase Volt(V)' },
  { name: 'R-Phase Amp(A)', prop: 'R-Phase Amp(A)' },
  { name: 'Y-Phase Amp(A)', prop: 'Y-Phase Amp(A)' },
  { name: 'B-Phase Amp(A)', prop: 'B-Phase Amp(A)' },
  { name: 'Grid Freq(Hz)', prop: 'Grid Freq(Hz)' },
  { name: 'Grid Power(kW)', prop: 'Grid Power(kW)' },
  { name: 'Today Grid Energy Export(kWh)', prop: 'Today Grid Energy Export(kWh)' },
  { name: 'Today GSC Hour(Hr)', prop: 'Today GSC Hour(Hr)' },
  { name: 'Today Grid Error Time', prop: 'Today Grid Error Time' },
  { name: 'Total Grid Energy Export(kWh)', prop: 'Total Grid Energy Export(kWh)' },
  { name: 'Total GSC Hour(Hr)', prop: 'Total GSC Hour(Hr)' },
  { name: 'Today Grid Energy Import', prop: 'Today Grid Energy Import' },
  { name: 'Total Grid Energy Import', prop: 'Total Grid Energy Import' }
];  